#!/bin/bash
#
# Autor= João Batista Ribeiro
# Bugs, Agradecimentos, Críticas "construtivas"
# me envie um e-mail. Ficarei Grato!
# e-mail: joao42lbatista@gmail.com
#
# Este programa é um software livre: você pode redistribuí-lo e/ou
# modificá-lo sob os termos da Licença Pública Geral GNU (GPL)
# conforme publicada pela Free Software Foundation, tanto a versão 3
# da licença, como (a seu critério) qualquer versão posterior.
#
# Este programa é distribuído na esperança de que seja útil,
# mas SEM NENHUMA GARANTIA; nem mesmo a garantia implícita de
# COMERCIABILIDADE ou ADEQUAÇÃO A UM PROPÓSITO ESPECÍFICO.
# Consulte a Licença Pública Geral do GNU para mais detalhes.
#
# Description: personal_bashrc with personal bashrc configuration
#
# Last update: 18/02/2026
#

# Run: check_for_update_progs_JBs.sh all # https://github.com/ryuuzaki42/03_Slackware_JB_Packages/
alias check_for_update_progs_JBs.sh='/media/sda2/git_clone/03_Slackware_JB_Packages/\
check_for_update_progs_JBs.sh'

# Run: ffsubsync ffs *.m* -i *.srt -o a.srt; smartsynchronize *.srt # https://github.com/ryuuzaki42/FFsubsync_AppImage
alias ffsubsync='/media/sda2/os/gnu_linux/slackware15.0/AppImage/FFsubsync-*_JB-x86_64.AppImage'

# Run: witr # https://github.com/ryuuzaki42/witr_AppImage
alias witr='/media/sda2/os/gnu_linux/slackware15.0/AppImage/witr-*_JB-x86_64.AppImage'

# VSCodium - codium - code as VSCode
alias code='/media/sda2/os/gnu_linux/slackware15.0/AppImage/VSCodium-*.AppImage'
#alias code='/media/sda2/home/j/.0installed/VSCodium/VSCodium-linux-x64-*/codium'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/media/sda2/home/j/.0installed/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/media/sda2/home/j/.0installed/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/media/sda2/home/j/.0installed/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/media/sda2/home/j/.0installed/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
