#!/bin/bash
# Autor= João Batista Ribeiro
# Bugs, Agradecimentos, Críticas "construtivas"
# me envie um e-mail. Ficarei Grato!
# e-mail: joao42lbatista@gmail.com
#
# Este programa é um software livre; você pode redistribui-lo e/ou
# modifica-lo dentro dos termos da Licença Pública Geral GNU como
# publicada pela Fundação do Software Livre (FSF); na versão 2 da
# Licença, ou (na sua opinião) qualquer versão.
#
# Este programa é distribuído na esperança que possa ser útil,
# mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a
# qualquer MERCADO ou APLICAÇÃO EM PARTICULAR.
#
# Veja a Licença Pública Geral GNU para mais detalhes.
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
#
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Description: personal_bashrc with personal bashrc configuration
#
# Last update: 30/10/2024
#

# Run: check_for_update_progs_JBs.sh all
alias check_for_update_progs_JBs.sh='/media/sda2/git_clone/03_Slackware_JB_Packages/\
check_for_update_progs_JBs.sh'

# Run: GitAhead . or GitAhead
alias GitAhead='/media/sda2/home/j/.0installed/GitAhead/GitAhead'

# Run: ffsubsync ffs *.m* -i *.srt -o a.srt
alias ffsubsync='/media/sda2/os/gnu_linux/slackware15.0/AppImage/FFsubsync-*_JB-x86_64.AppImage'

# VSCodium - codium - code as VSCode
#alias code='/media/sda2/os/gnu_linux/slackware15.0/AppImage/VSCodium-*.AppImage'
alias code='/media/sda2/home/j/.0installed/VSCodium/VSCodium-linux-x64-*/codium'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/media/sda2/home/j/.0installed/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/media/sda2/home/j/.0installed/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/media/sda2/home/j/.0installed/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/media/sda2/home/j/.0installed/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
